In [1]:
import numpy as np

In [2]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a = np.linspace(0,11,12)
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [33]:
a.shape

(12,)

In [35]:
a.reshape(2,6)

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

In [23]:
ls = [[1,2,3,4], [13,4,5,6]]

In [24]:
np.array(ls)

array([[ 1,  2,  3,  4],
       [13,  4,  5,  6]])

In [37]:
array = np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
array[2:3]

array([3])

In [44]:
np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [57]:
d = np.arange(0,40,1)
d = d.reshape(4,10)
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [67]:
slice_ = d[1:3, 1:3]
slice_

array([[11, 12],
       [21, 22]])

In [68]:
slice_[:] = 0
slice_

array([[0, 0],
       [0, 0]])

In [69]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [20,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [63]:
my_array = np.array([1,2,3,4])
my_array

array([1, 2, 3, 4])

In [64]:
my_array[:] = 10
my_array

array([10, 10, 10, 10])